apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi # Placeholder: Adjust to your needs
  storageClassName: immich-data-storage
