apiVersion: v1
kind: Service
metadata:
  name: immich-server-service
spec:
  type: LoadBalancer 
  selector:
    app: immich-server
  ports:
    - protocol: TCP
      port: 2283
      targetPort: 2283
