apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich
  template:
    metadata:
      labels:
        app: immich
    spec:
      containers:
        - name: immich
          image: ghcr.io/immich-app/immich-server:release
          env:
            - name: DB_DATA_LOCATION
              value: ./postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_USERNAME
              value: postgres
            - name: DB_DATABASE_NAME
              value: immich
            - name: IMMICH_VERSION
              value: release
            - name: url
              value: http://ghost.example.com
            - name: UPLOAD_LOCATION
              value: =/maps/pictures
          ports:
            - containerPort: 2283
