---
apiVersion: v1
kind: Service
metadata:
  name: immich-server-service
spec:
  type: LoadBalancer
  selector:
    app: immich-server
  ports:
    - protocol: TCP
      port: 84
      targetPort: 2283
---
apiVersion: v1
kind: Service
metadata:
  name: immich-db-service
spec:
  clusterIP: None
  selector:
    app: immich-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: immich-redis-service
spec:
  clusterIP: None 
  selector:
    app: immich-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
