apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
data:
  DB_USERNAME: "immich"
  DB_DATABASE_NAME: "immich"
  IMMICH_VERSION: "release"
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
type: Opaque
data:
  DB_PASSWORD: ""
