apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-db-deployment
  labels:
    app: immich-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-db
  template:
    metadata:
      labels:
        app: immich-db
    spec:
      containers:
        - name: postgres
          image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:5f6a838e4e44c8e0e019d0ebfe3ee8952b69afc2809b2c25f7b0119641978e91
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
            - name: shm-volume
              mountPath: /dev/shm
          envFrom:
            - secretRef:
                name: immich-secret
            - configMapRef:
                name: immich-config
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: immich-db-pvc
        - name: shm-volume
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
